//! Direct-translation Wireshark dissector generator (Lua 5.2).
//!
//! Each IR state becomes a readable Lua function with a runtime bit
//! cursor; diagnose-mode behavior (partial tree + expert info +
//! payload rendering) is compiled in. Deliberately rehearses the
//! slice-4 C emitter's shape.
//!
//! Loud caps (generation errors, never silent): referenced fields and
//! masked select keys wider than 32 bits (Lua 5.2 bit32 limit),
//! constants above 2^53 (Lua number exactness), variable-length fields
//! at non-byte-aligned offsets, states with alignment-conflicting
//! entries needing typed ProtoFields.

use crate::ir::pb;
use anyhow::{bail, Result};
use std::collections::{HashMap, HashSet};
use std::fmt::Write;

pub fn generate_lua(ir: &pb::Ir) -> Result<String> {
    let parser = ir
        .parser
        .as_ref()
        .ok_or_else(|| anyhow::anyhow!("ir has no parser"))?;
    let proto = format!("pakeles_{}", parser.name);
    let header_types: HashMap<&str, &pb::HeaderType> = parser
        .header_types
        .iter()
        .map(|h| (h.name.as_str(), h))
        .collect();

    let referenced = referenced_fields(parser);
    let entry_align = entry_alignments(parser);

    let mut out = String::new();
    let w = &mut out;
    writeln!(
        w,
        "-- Generated by pakeles from `{}` (ir {}).",
        parser.name, ir.ir_version
    )?;
    writeln!(w, "-- Do not edit: regenerate with `pakeles gen lua`.")?;
    writeln!(
        w,
        "-- Requires Lua 5.2 (bit32); length arithmetic is signed —"
    )?;
    writeln!(
        w,
        "-- negative computed lengths are treated as out of bounds,"
    )?;
    writeln!(w, "-- matching the reference interpreter's outcome.")?;
    writeln!(
        w,
        "local p = Proto(\"{proto}\", \"Pakeles {}\")",
        parser.name
    )?;
    writeln!(w)?;
    writeln!(
        w,
        "local ef_error = ProtoExpert.new(\"{proto}.malformed\", \"Malformed\", expert.group.MALFORMED, expert.severity.ERROR)"
    )?;
    writeln!(
        w,
        "local ef_info = ProtoExpert.new(\"{proto}.boundary\", \"Payload boundary\", expert.group.PROTOCOL, expert.severity.NOTE)"
    )?;
    writeln!(w, "p.experts = {{ ef_error, ef_info }}")?;
    writeln!(w)?;

    // ProtoField declarations per (instance, field). Each header
    // instance also gets an FT_NONE subtree field: unique JSON keys
    // (text-only subtrees all render as "_ws.lua.text" and collide).
    let mut pf_names: Vec<String> = Vec::new();
    let mut pf_decl = String::new();
    for state in &parser.states {
        for ex in &state.extracts {
            let ht = header_types[ex.header_type.as_str()];
            let inst = instance_name(ex);
            let hdr_var = format!("f_hdr_{inst}");
            if !pf_names.contains(&hdr_var) {
                pf_decl.push_str(&format!(
                    "local {hdr_var} = ProtoField.none(\"{proto}.{inst}\", \"{inst}\")\n"
                ));
                pf_names.push(hdr_var);
            }
            for field in &ht.fields {
                let var = pf_var(inst, &field.name);
                if pf_names.contains(&var) {
                    continue; // same instance extracted in several states
                }
                let abbr = format!("{proto}.{inst}.{}", field.name);
                let display = field.display.clone().unwrap_or_default();
                let name = if display.name.is_empty() {
                    field.name.clone()
                } else {
                    display.name.clone()
                };
                let aligned =
                    field_alignment(parser, &entry_align, state, inst, &field.name) == Some(0);
                let decl = protofield_decl(&abbr, &name, field, &display, aligned)?;
                pf_decl.push_str(&format!("local {var} = {decl}\n"));
                pf_names.push(var);
            }
        }
    }
    let payload_pf = "f_payload".to_string();
    pf_decl.push_str(&format!(
        "local {payload_pf} = ProtoField.bytes(\"{proto}.payload\", \"Payload\")\n"
    ));
    pf_names.push(payload_pf);
    w.push_str(&pf_decl);
    writeln!(w, "p.fields = {{ {} }}", pf_names.join(", "))?;
    writeln!(w)?;
    writeln!(w, "local states = {{}}")?;
    writeln!(w)?;
    writeln!(w, "local function add_payload(buf, tree, off)")?;
    writeln!(w, "  if off < buf:len() * 8 then")?;
    writeln!(w, "    tree:add(f_payload, buf(math.floor(off / 8)))")?;
    writeln!(w, "  end")?;
    writeln!(w, "end")?;
    writeln!(w)?;

    for state in &parser.states {
        emit_state(w, parser, &header_types, &referenced, &entry_align, state)?;
    }

    writeln!(w, "function p.dissector(buf, pinfo, tree)")?;
    writeln!(w, "  local root = tree:add(p, buf())")?;
    writeln!(w, "  states.{}(buf, pinfo, root, 0, 0)", parser.start_state)?;
    writeln!(w, "end")?;
    writeln!(w)?;
    writeln!(
        w,
        "-- Postdissector: runs on every frame after built-in dissection,"
    )?;
    writeln!(
        w,
        "-- so our tree appears alongside Wireshark's own — side-by-side"
    )?;
    writeln!(
        w,
        "-- comparison for free, no dissector-table precedence fights."
    )?;
    writeln!(w, "register_postdissector(p)")?;
    Ok(out)
}

fn instance_name(ex: &pb::Extract) -> &str {
    if ex.instance.is_empty() {
        &ex.header_type
    } else {
        &ex.instance
    }
}

fn pf_var(inst: &str, field: &str) -> String {
    format!("f_{inst}_{field}")
}

fn val_var(inst: &str, field: &str) -> String {
    format!("v_{inst}_{field}")
}

/// (instance, field) pairs referenced by any expression in the parser.
fn referenced_fields(parser: &pb::Parser) -> HashSet<(String, String)> {
    let mut out = HashSet::new();
    let mut walk = |e: &pb::Expr| collect_refs(e, &mut out);
    for ht in &parser.header_types {
        for f in &ht.fields {
            if let Some(pb::field_width::Width::ByteLen(e)) =
                f.width.as_ref().and_then(|w| w.width.as_ref())
            {
                walk(e);
            }
        }
    }
    for s in &parser.states {
        if let Some(pb::transition::Kind::Select(sel)) =
            s.transition.as_ref().and_then(|t| t.kind.as_ref())
        {
            for k in &sel.keys {
                walk(k);
            }
        }
    }
    out
}

fn collect_refs(e: &pb::Expr, out: &mut HashSet<(String, String)>) {
    match &e.kind {
        Some(pb::expr::Kind::Field(r)) => {
            out.insert((r.header.clone(), r.field.clone()));
        }
        Some(pb::expr::Kind::Bin(b)) => {
            if let Some(l) = &b.lhs {
                collect_refs(l, out);
            }
            if let Some(r) = &b.rhs {
                collect_refs(r, out);
            }
        }
        _ => {}
    }
}

/// Static state-entry bit alignment (mod 8): fixpoint over the graph.
/// `Some(a)` = every entry arrives with cursor ≡ a (mod 8); `None` =
/// conflicting or unknown.
fn entry_alignments(parser: &pb::Parser) -> HashMap<String, Option<u32>> {
    let states: HashMap<&str, &pb::State> =
        parser.states.iter().map(|s| (s.name.as_str(), s)).collect();
    let mut align: HashMap<String, Option<u32>> = HashMap::new();
    align.insert(parser.start_state.clone(), Some(0));
    let mut work = vec![parser.start_state.clone()];
    while let Some(name) = work.pop() {
        let Some(state) = states.get(name.as_str()) else {
            continue;
        };
        let entry = align[&name];
        // Alignment delta across the state: fixed widths only (var
        // fields add whole bytes — alignment-preserving).
        let mut delta = 0u32;
        for ex in &state.extracts {
            if let Some(ht) = parser
                .header_types
                .iter()
                .find(|h| h.name == ex.header_type)
            {
                for f in &ht.fields {
                    if let Some(pb::field_width::Width::Bits(n)) =
                        f.width.as_ref().and_then(|w| w.width.as_ref())
                    {
                        delta = (delta + n) % 8;
                    }
                }
            }
        }
        let exit = entry.map(|a| (a + delta) % 8);
        for succ in successor_states(state) {
            let merged = match align.get(&succ) {
                None => exit,
                Some(prev) if *prev == exit => continue,
                Some(_) => None,
            };
            align.insert(succ.clone(), merged);
            work.push(succ);
        }
    }
    align
}

fn successor_states(s: &pb::State) -> Vec<String> {
    let mut out = Vec::new();
    let mut push = |t: &pb::Target| {
        if let Some(pb::target::Kind::State(n)) = &t.kind {
            out.push(n.clone());
        }
    };
    match s.transition.as_ref().and_then(|t| t.kind.as_ref()) {
        Some(pb::transition::Kind::Direct(t)) => push(t),
        Some(pb::transition::Kind::Select(sel)) => {
            for arm in &sel.arms {
                if let Some(t) = &arm.next {
                    push(t);
                }
            }
            if let Some(t) = &sel.default_target {
                push(t);
            }
        }
        None => {}
    }
    out
}

/// Absolute alignment (mod 8) of a field's start, if statically known.
fn field_alignment(
    parser: &pb::Parser,
    entry_align: &HashMap<String, Option<u32>>,
    state: &pb::State,
    inst: &str,
    field_name: &str,
) -> Option<u32> {
    let entry = (*entry_align.get(&state.name)?)?;
    let mut off = entry;
    for ex in &state.extracts {
        let ht = parser
            .header_types
            .iter()
            .find(|h| h.name == ex.header_type)?;
        let this_inst = instance_name(ex);
        for f in &ht.fields {
            if this_inst == inst && f.name == field_name {
                return Some(off % 8);
            }
            if let Some(pb::field_width::Width::Bits(n)) =
                f.width.as_ref().and_then(|w| w.width.as_ref())
            {
                off = (off + n) % 8;
            }
            // var fields: whole bytes, alignment unchanged
        }
    }
    None
}

fn protofield_decl(
    abbr: &str,
    name: &str,
    field: &pb::Field,
    display: &pb::Display,
    byte_aligned: bool,
) -> Result<String> {
    let format = pb::DisplayFormat::try_from(display.format).unwrap_or_default();
    let width = match field.width.as_ref().and_then(|w| w.width.as_ref()) {
        Some(pb::field_width::Width::Bits(n)) => Some(*n),
        _ => None,
    };
    if let Some(width) = width {
        match format {
            pb::DisplayFormat::Ether if width == 48 && byte_aligned => {
                return Ok(format!("ProtoField.ether(\"{abbr}\", \"{name}\")"));
            }
            pb::DisplayFormat::Ipv4 if width == 32 && byte_aligned => {
                return Ok(format!("ProtoField.ipv4(\"{abbr}\", \"{name}\")"));
            }
            _ => {}
        }
        let ctor = match width {
            1..=8 => "uint8",
            9..=16 => "uint16",
            17..=24 => "uint24",
            25..=32 => "uint32",
            _ => "uint64",
        };
        let base = match format {
            pb::DisplayFormat::Dec => "base.DEC",
            // base.BIN doesn't exist for integers; HEX is the closest.
            _ => "base.HEX",
        };
        let labels = if display.value_labels.is_empty() {
            String::new()
        } else {
            let entries: Vec<String> = display
                .value_labels
                .iter()
                .map(|vl| format!("[{}] = \"{}\"", vl.value, vl.label))
                .collect();
            format!(", {{ {} }}", entries.join(", "))
        };
        Ok(format!(
            "ProtoField.{ctor}(\"{abbr}\", \"{name}\", {base}{labels})"
        ))
    } else {
        Ok(format!("ProtoField.bytes(\"{abbr}\", \"{name}\")"))
    }
}

fn expr_lua(e: &pb::Expr, referenced: &HashSet<(String, String)>) -> Result<String> {
    match e.kind.as_ref() {
        Some(pb::expr::Kind::Constant(v)) => {
            if *v > (1u64 << 53) {
                bail!("constant {v} exceeds Lua number exactness (2^53)");
            }
            Ok(format!("{v}"))
        }
        Some(pb::expr::Kind::Field(r)) => {
            debug_assert!(referenced.contains(&(r.header.clone(), r.field.clone())));
            Ok(val_var(&r.header, &r.field))
        }
        Some(pb::expr::Kind::Bin(b)) => {
            let l = expr_lua(b.lhs.as_deref().unwrap(), referenced)?;
            let r = expr_lua(b.rhs.as_deref().unwrap(), referenced)?;
            let op = pb::BinOpKind::try_from(b.op).unwrap_or_default();
            Ok(match op {
                pb::BinOpKind::Add => format!("({l} + {r})"),
                pb::BinOpKind::Sub => format!("({l} - {r})"),
                pb::BinOpKind::Mul => format!("({l} * {r})"),
                pb::BinOpKind::Shl => format!("({l} * 2 ^ {r})"),
                pb::BinOpKind::Shr => format!("math.floor({l} / 2 ^ {r})"),
                pb::BinOpKind::And => format!("bit32.band({l}, {r})"),
                pb::BinOpKind::Or => format!("bit32.bor({l}, {r})"),
                pb::BinOpKind::Unspecified => bail!("unspecified binop"),
            })
        }
        None => bail!("empty expression"),
    }
}

fn entry_lua(entry: &pb::KeysetEntry, key_lua: &str, key_width: Option<u32>) -> Result<String> {
    match entry.kind.as_ref() {
        Some(pb::keyset_entry::Kind::Value(v)) => Ok(format!("{key_lua} == {v}")),
        Some(pb::keyset_entry::Kind::Masked(m)) => {
            if key_width.is_none_or(|w| w > 32) {
                bail!("masked select keys wider than 32 bits are not supported by the Lua backend yet");
            }
            Ok(format!(
                "bit32.band({key_lua}, {}) == {}",
                m.mask,
                m.value & m.mask
            ))
        }
        Some(pb::keyset_entry::Kind::Range(r)) => {
            Ok(format!("({key_lua} >= {} and {key_lua} <= {})", r.lo, r.hi))
        }
        None => Ok("false".into()),
    }
}

fn target_lua(target: &pb::Target, indent: &str, w: &mut String) -> Result<()> {
    match target.kind.as_ref() {
        Some(pb::target::Kind::State(name)) => {
            writeln!(
                w,
                "{indent}return states.{name}(buf, pinfo, tree, off, depth)"
            )?;
        }
        Some(pb::target::Kind::Accept(_)) => {
            writeln!(w, "{indent}add_payload(buf, tree, off)")?;
            writeln!(w, "{indent}return off")?;
        }
        Some(pb::target::Kind::Reject(r)) => {
            let info = r.annotations.get("severity").map(String::as_str) == Some("info");
            if info {
                writeln!(w, "{indent}add_payload(buf, tree, off)")?;
                writeln!(
                    w,
                    "{indent}tree:add_proto_expert_info(ef_info, \"{}\")",
                    r.reason
                )?;
            } else {
                writeln!(
                    w,
                    "{indent}tree:add_proto_expert_info(ef_error, \"{}\")",
                    r.reason
                )?;
            }
            writeln!(w, "{indent}return off")?;
        }
        None => bail!("empty target"),
    }
    Ok(())
}

fn emit_state(
    w: &mut String,
    parser: &pb::Parser,
    header_types: &HashMap<&str, &pb::HeaderType>,
    referenced: &HashSet<(String, String)>,
    entry_align: &HashMap<String, Option<u32>>,
    state: &pb::State,
) -> Result<()> {
    writeln!(
        w,
        "function states.{}(buf, pinfo, tree, off, depth)",
        state.name
    )?;
    writeln!(w, "  depth = depth + 1")?;
    writeln!(w, "  if depth > {} then", parser.max_depth)?;
    writeln!(
        w,
        "    tree:add_proto_expert_info(ef_error, \"max depth exceeded\")"
    )?;
    writeln!(w, "    return off")?;
    writeln!(w, "  end")?;
    writeln!(w, "  local avail = buf:len() * 8")?;

    for ex in &state.extracts {
        let ht = header_types[ex.header_type.as_str()];
        let inst = instance_name(ex);
        // FT_NONE subtree under the single proto root: unique JSON key
        // per header instance.
        writeln!(
            w,
            "  local hdr_{inst} = tree:add(f_hdr_{inst}, buf(math.floor(off / 8)))"
        )?;
        for field in &ht.fields {
            let pf = pf_var(inst, &field.name);
            match field.width.as_ref().and_then(|x| x.width.as_ref()) {
                Some(pb::field_width::Width::Bits(n)) => {
                    let n = *n;
                    writeln!(w, "  if off + {n} > avail then")?;
                    writeln!(
                        w,
                        "    hdr_{inst}:add_proto_expert_info(ef_error, \"out of bounds in {inst}.{}\")",
                        field.name
                    )?;
                    writeln!(w, "    return off")?;
                    writeln!(w, "  end")?;
                    let cover =
                        format!("buf(math.floor(off / 8), math.floor((off % 8 + {n} + 7) / 8))");
                    let is_ref = referenced.contains(&(inst.to_string(), field.name.clone()));
                    if is_ref && n > 32 {
                        bail!(
                            "referenced field `{inst}.{}` wider than 32 bits is not supported by the Lua backend yet",
                            field.name
                        );
                    }
                    let aligned =
                        field_alignment(parser, entry_align, state, inst, &field.name) == Some(0);
                    let format = field
                        .display
                        .as_ref()
                        .and_then(|d| pb::DisplayFormat::try_from(d.format).ok())
                        .unwrap_or_default();
                    let typed_range_add = aligned
                        && ((format == pb::DisplayFormat::Ether && n == 48)
                            || (format == pb::DisplayFormat::Ipv4 && n == 32)
                            || n > 32);
                    if is_ref {
                        let v = val_var(inst, &field.name);
                        writeln!(w, "  local {v} = buf():bitfield(off, {n})")?;
                        writeln!(w, "  hdr_{inst}:add({pf}, {cover}, {v})")?;
                    } else if typed_range_add {
                        // Byte-aligned: exact range, Wireshark decodes.
                        writeln!(
                            w,
                            "  hdr_{inst}:add({pf}, buf(math.floor(off / 8), {}))",
                            n.div_ceil(8)
                        )?;
                    } else {
                        writeln!(
                            w,
                            "  hdr_{inst}:add({pf}, {cover}, buf():bitfield(off, {n}))"
                        )?;
                    }
                    writeln!(w, "  off = off + {n}")?;
                }
                Some(pb::field_width::Width::ByteLen(expr)) => {
                    let aligned =
                        field_alignment(parser, entry_align, state, inst, &field.name) == Some(0);
                    if !aligned {
                        bail!(
                            "variable-length field `{inst}.{}` is not statically byte-aligned",
                            field.name
                        );
                    }
                    let len = format!("len_{inst}_{}", field.name);
                    writeln!(w, "  local {len} = {}", expr_lua(expr, referenced)?)?;
                    writeln!(w, "  if {len} < 0 or off + {len} * 8 > avail then")?;
                    writeln!(
                        w,
                        "    hdr_{inst}:add_proto_expert_info(ef_error, \"out of bounds in {inst}.{}\")",
                        field.name
                    )?;
                    writeln!(w, "    return off")?;
                    writeln!(w, "  end")?;
                    writeln!(w, "  if {len} > 0 then")?;
                    writeln!(
                        w,
                        "    hdr_{inst}:add({pf}, buf(math.floor(off / 8), {len}))"
                    )?;
                    writeln!(w, "  end")?;
                    writeln!(w, "  off = off + {len} * 8")?;
                }
                None => bail!("field `{}` has no width", field.name),
            }
        }
    }

    match state.transition.as_ref().and_then(|t| t.kind.as_ref()) {
        None => bail!("state `{}` has no transition", state.name),
        Some(pb::transition::Kind::Direct(t)) => {
            target_lua(t, "  ", w)?;
        }
        Some(pb::transition::Kind::Select(sel)) => {
            let keys: Vec<String> = sel
                .keys
                .iter()
                .map(|k| expr_lua(k, referenced))
                .collect::<Result<_>>()?;
            let key_widths: Vec<Option<u32>> =
                sel.keys.iter().map(|k| key_bit_width(parser, k)).collect();
            for (i, arm) in sel.arms.iter().enumerate() {
                let conds: Vec<String> = arm
                    .entries
                    .iter()
                    .zip(keys.iter().zip(&key_widths))
                    .map(|(e, (k, wd))| entry_lua(e, k, *wd))
                    .collect::<Result<_>>()?;
                let kw = if i == 0 { "if" } else { "elseif" };
                writeln!(w, "  {kw} {} then", conds.join(" and "))?;
                target_lua(
                    arm.next
                        .as_ref()
                        .ok_or_else(|| anyhow::anyhow!("arm without target"))?,
                    "    ",
                    w,
                )?;
            }
            if sel.arms.is_empty() {
                match sel.default_target.as_ref() {
                    Some(t) => target_lua(t, "  ", w)?,
                    None => {
                        writeln!(
                            w,
                            "  tree:add_proto_expert_info(ef_error, \"no matching select arm\")"
                        )?;
                        writeln!(w, "  return off")?;
                    }
                }
            } else {
                writeln!(w, "  else")?;
                match sel.default_target.as_ref() {
                    Some(t) => target_lua(t, "    ", w)?,
                    None => {
                        writeln!(
                            w,
                            "    tree:add_proto_expert_info(ef_error, \"no matching select arm\")"
                        )?;
                        writeln!(w, "    return off")?;
                    }
                }
                writeln!(w, "  end")?;
            }
        }
    }
    writeln!(w, "end")?;
    writeln!(w)?;
    Ok(())
}

/// Bit width of a select key when it is a plain field ref.
fn key_bit_width(parser: &pb::Parser, key: &pb::Expr) -> Option<u32> {
    if let Some(pb::expr::Kind::Field(r)) = &key.kind {
        for s in &parser.states {
            for ex in &s.extracts {
                if instance_name(ex) == r.header {
                    let ht = parser
                        .header_types
                        .iter()
                        .find(|h| h.name == ex.header_type)?;
                    let f = ht.fields.iter().find(|f| f.name == r.field)?;
                    if let Some(pb::field_width::Width::Bits(b)) =
                        f.width.as_ref().and_then(|x| x.width.as_ref())
                    {
                        return Some(*b);
                    }
                }
            }
        }
    }
    None
}

/// Run tshark with args, dropping root (root disables Lua scripts).
#[cfg(test)]
fn tshark_unprivileged(args: &[&str]) -> Result<std::process::Output> {
    let script = r#"if [ "$(id -u)" = "0" ]; then
  exec env HOME=/tmp setpriv --reuid=nobody --regid=nogroup --clear-groups tshark "$@"
else
  exec tshark "$@"
fi"#;
    Ok(std::process::Command::new("sh")
        .arg("-c")
        .arg(script)
        .arg("tshark")
        .args(args)
        .output()?)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::examples::{eth_ipvx_l4, linux_flow_dissector};

    #[test]
    fn committed_dissector_current() {
        let lua = generate_lua(&eth_ipvx_l4()).unwrap();
        assert!(lua.contains("function states.parse_ipv4"));
        assert!(lua.contains("ProtoField.ether"));
        assert!(lua.contains("[6] = \"TCP\""));
        let committed = std::fs::read_to_string("examples/eth_ipvx_l4/gen/dissector.lua").unwrap();
        assert_eq!(
            lua, committed,
            "examples/ drifted; regenerate: ./dev.sh cargo run --bin gen_examples"
        );
    }

    /// The full loop: symbolic vectors -> pcap -> tshark running our
    /// generated dissector -> JSON diffed against expected fields.
    fn generated_dissector_conformance_suite(ir: &pb::Ir) {
        if std::process::Command::new("tshark")
            .arg("--version")
            .output()
            .is_err()
        {
            eprintln!("skipping: tshark not available");
            return;
        }
        let parser = ir.parser.as_ref().unwrap();
        let name = parser.name.clone();
        let proto = format!("pakeles_{}", parser.name);
        let suite = crate::testvec::suite_from_json(
            &std::fs::read_to_string(format!("examples/{name}/conformance/vectors.json")).unwrap(),
        )
        .unwrap();
        let (packets, indices) = crate::testvec::suite_to_packets(&suite);

        let dir = std::env::temp_dir();
        let lua_path = dir.join(format!("pakeles_conf_{name}_{}.lua", std::process::id()));
        let pcap_path = dir.join(format!("pakeles_conf_{name}_{}.pcap", std::process::id()));
        std::fs::write(&lua_path, generate_lua(ir).unwrap()).unwrap();
        crate::pcapio::write_pcap(&pcap_path, &packets).unwrap();

        let out = tshark_unprivileged(&[
            "-X",
            &format!("lua_script:{}", lua_path.display()),
            "-r",
            pcap_path.to_str().unwrap(),
            "-T",
            "json",
        ])
        .unwrap();
        assert!(
            out.status.success(),
            "tshark failed: {}",
            String::from_utf8_lossy(&out.stderr)
        );
        let dissected: Vec<serde_json::Value> = serde_json::from_slice(&out.stdout).unwrap();
        assert_eq!(dissected.len(), packets.len());

        let field_meta = |inst: &str, name: &str| -> Option<&pb::Field> {
            parser.states.iter().find_map(|s| {
                s.extracts.iter().find_map(|ex| {
                    (instance_name(ex) == inst)
                        .then(|| {
                            parser
                                .header_types
                                .iter()
                                .find(|h| h.name == ex.header_type)?
                                .fields
                                .iter()
                                .find(|f| f.name == name)
                        })
                        .flatten()
                })
            })
        };

        let mut mismatches: Vec<String> = Vec::new();
        let mut compared = 0usize;
        for (dis, &vi) in dissected.iter().zip(&indices) {
            let vector = &suite.vectors[vi];
            let layers = &dis["_source"]["layers"];
            assert!(
                layers.get(&proto).is_some(),
                "{}: our proto layer missing",
                vector.id
            );
            // Accept vectors carry expected headers in the schema;
            // reject vectors don't, so re-derive them from the
            // reference interpreter (which the suite replay already
            // validates).
            let expected_headers = match vector.expected.as_ref().and_then(|e| e.outcome.as_ref()) {
                Some(crate::testvec::pb::expected::Outcome::Accept(a)) => a
                    .headers
                    .iter()
                    .map(|h| {
                        (
                            h.instance.clone(),
                            h.fields
                                .iter()
                                .map(|f| (f.name.clone(), f.value.clone()))
                                .collect::<Vec<_>>(),
                        )
                    })
                    .collect::<Vec<_>>(),
                _ => {
                    let (bits, _) = crate::testvec::Bits::from_pb(vector.packet.as_ref().unwrap());
                    let res = crate::interp::run_bits(ir, &bits).unwrap();
                    headers_to_expected(&crate::codegen::c::last_headers_by_instance(&res.headers))
                }
            };
            for (inst, fields) in &expected_headers {
                for (fname, fval) in fields {
                    let key = format!("{proto}.{inst}.{fname}");
                    let raw = crate::oracle::lookup(layers, &key);
                    match fval {
                        Some(crate::testvec::pb::expected_field::Value::Uint(want)) => {
                            compared += 1;
                            let format = field_meta(inst, fname)
                                .and_then(|f| f.display.as_ref())
                                .and_then(|d| pb::DisplayFormat::try_from(d.format).ok())
                                .unwrap_or_default();
                            let got = raw.and_then(|r| crate::oracle::normalize_typed(r, format));
                            if got != Some(*want) {
                                mismatches.push(format!(
                                    "{}: {key} ours={want} tshark={raw:?}",
                                    vector.id
                                ));
                            }
                        }
                        Some(crate::testvec::pb::expected_field::Value::BytesHex(want)) => {
                            if want.is_empty() {
                                continue; // zero-length fields aren't added
                            }
                            compared += 1;
                            let got: String = raw
                                .unwrap_or_default()
                                .chars()
                                .filter(|c| *c != ':')
                                .collect::<String>()
                                .to_lowercase();
                            if got != *want {
                                mismatches
                                    .push(format!("{}: {key} ours={want} tshark={got}", vector.id));
                            }
                        }
                        None => {}
                    }
                }
            }
        }
        let _ = std::fs::remove_file(&lua_path);
        let _ = std::fs::remove_file(&pcap_path);
        assert!(compared > 500, "suspiciously few comparisons: {compared}");
        assert!(
            mismatches.is_empty(),
            "{} mismatches:\n{}",
            mismatches.len(),
            mismatches.join("\n")
        );
    }

    #[test]
    fn generated_dissector_conformance() {
        generated_dissector_conformance_suite(&eth_ipvx_l4());
    }

    #[test]
    fn generated_dissector_conformance_flow_dissector() {
        generated_dissector_conformance_suite(&linux_flow_dissector());
    }

    type ExpectedFields = Vec<(String, Option<crate::testvec::pb::expected_field::Value>)>;

    /// interp headers -> the (inst, fields) shape used above.
    fn headers_to_expected(
        headers: &[&crate::interp::ParsedHeader],
    ) -> Vec<(String, ExpectedFields)> {
        headers
            .iter()
            .map(|h| {
                (
                    h.instance.clone(),
                    h.fields
                        .iter()
                        .map(|f| {
                            let v = match &f.value {
                                crate::interp::FieldValue::Uint(u) => {
                                    crate::testvec::pb::expected_field::Value::Uint(*u)
                                }
                                crate::interp::FieldValue::Bytes(b) => {
                                    crate::testvec::pb::expected_field::Value::BytesHex(
                                        crate::testvec::hex_encode(b),
                                    )
                                }
                            };
                            (f.name.clone(), Some(v))
                        })
                        .collect(),
                )
            })
            .collect()
    }

    #[test]
    fn wide_masked_key_is_generation_error() {
        use crate::builder::*;
        let ir = ParserBuilder::new("wide", 2)
            .header(HeaderTypeBuilder::new("h").bits("f", 48))
            .state(StateBuilder::new("a").extract("h").select(
                vec![f("h", "f")],
                vec![arm(vec![masked(0, 0xFF)], to("b"))],
                reject("no"),
            ))
            .state(StateBuilder::new("b").accept())
            .start("a")
            .build()
            .unwrap();
        let err = generate_lua(&ir).unwrap_err();
        assert!(err.to_string().contains("wider than 32 bits"));
    }
}
