//! Documentation generator: IR + Display annotations -> markdown.
//! Dogfoods the annotation layer — everything shown here comes from
//! the description itself, nothing is hand-maintained.

use crate::ir::pb;
use anyhow::Result;
use std::fmt::Write;

pub fn generate_markdown(ir: &pb::Ir) -> Result<String> {
    let parser = ir
        .parser
        .as_ref()
        .ok_or_else(|| anyhow::anyhow!("ir has no parser"))?;
    let mut out = String::new();
    let w = &mut out;
    writeln!(w, "# `{}`", parser.name)?;
    writeln!(w)?;
    writeln!(
        w,
        "Generated by `pakeles doc` from IR version {}. Parse depth bound: {}.",
        ir.ir_version, parser.max_depth
    )?;

    for ht in &parser.header_types {
        writeln!(w)?;
        writeln!(w, "## Header `{}`", ht.name)?;
        writeln!(w)?;
        writeln!(w, "| Field | Bits | Format | Name | Labels | Notes |")?;
        writeln!(w, "|---|---|---|---|---|---|")?;
        for f in &ht.fields {
            let width = match f.width.as_ref().and_then(|x| x.width.as_ref()) {
                Some(pb::field_width::Width::Bits(n)) => n.to_string(),
                Some(pb::field_width::Width::ByteLen(e)) => {
                    format!("`{}` bytes", crate::viz::expr_text(e))
                }
                None => "?".into(),
            };
            let d = f.display.clone().unwrap_or_default();
            let format = match pb::DisplayFormat::try_from(d.format).unwrap_or_default() {
                pb::DisplayFormat::Dec => "dec",
                pb::DisplayFormat::Hex => "hex",
                pb::DisplayFormat::Bin => "bin",
                pb::DisplayFormat::Ipv4 => "IPv4",
                pb::DisplayFormat::Ipv6 => "IPv6",
                pb::DisplayFormat::Ether => "MAC",
                pb::DisplayFormat::Unspecified => "",
            };
            let labels = d
                .value_labels
                .iter()
                .map(|vl| format!("{}={}", vl.value, vl.label))
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(
                w,
                "| `{}` | {} | {} | {} | {} | {} |",
                f.name, width, format, d.name, labels, d.doc
            )?;
        }
    }

    writeln!(w)?;
    writeln!(w, "## Parse graph")?;
    writeln!(w)?;
    writeln!(w, "Start state: `{}`.", parser.start_state)?;
    writeln!(w)?;
    for s in &parser.states {
        let extracts = s
            .extracts
            .iter()
            .map(|e| {
                if e.instance.is_empty() {
                    e.header_type.clone()
                } else {
                    e.instance.clone()
                }
            })
            .collect::<Vec<_>>()
            .join(", ");
        write!(w, "- **`{}`**", s.name)?;
        if !extracts.is_empty() {
            write!(w, " — extracts {extracts}")?;
        }
        match s.transition.as_ref().and_then(|t| t.kind.as_ref()) {
            Some(pb::transition::Kind::Direct(t)) => {
                writeln!(w, "; then {}", target_text(t))?;
            }
            Some(pb::transition::Kind::Select(sel)) => {
                writeln!(w, "; selects on {}:", keys_text(&sel.keys))?;
                for arm in &sel.arms {
                    let entries = arm
                        .entries
                        .iter()
                        .zip(&sel.keys)
                        .map(|(e, k)| crate::viz::entry_text(k, e))
                        .collect::<Vec<_>>()
                        .join(" && ");
                    let next = arm.next.as_ref().map(target_text).unwrap_or_default();
                    writeln!(w, "  - {entries} → {next}")?;
                }
                if let Some(t) = &sel.default_target {
                    writeln!(w, "  - otherwise → {}", target_text(t))?;
                }
            }
            None => writeln!(w)?,
        }
    }
    Ok(out)
}

fn keys_text(keys: &[pb::Expr]) -> String {
    keys.iter()
        .map(|k| format!("`{}`", crate::viz::expr_text(k)))
        .collect::<Vec<_>>()
        .join(", ")
}

fn target_text(t: &pb::Target) -> String {
    match t.kind.as_ref() {
        Some(pb::target::Kind::State(s)) => format!("`{s}`"),
        Some(pb::target::Kind::Accept(_)) => "**accept**".into(),
        Some(pb::target::Kind::Reject(r)) => {
            let info = r.annotations.get("severity").map(String::as_str) == Some("info");
            if info {
                format!("payload boundary (*{}*)", r.reason)
            } else {
                format!("**reject** (*{}*)", r.reason)
            }
        }
        None => "?".into(),
    }
}

#[cfg(test)]
mod tests {
    #[test]
    fn markdown_snapshot() {
        let md = super::generate_markdown(&crate::examples::eth_ipv4_tcp()).unwrap();
        assert!(md.contains("| `ttl` | 8 | dec | Time to Live |"));
        assert!(md.contains("payload boundary"));
        insta::assert_snapshot!(md);
    }
}
